# Generated by Django 3.2.18 on 2023-02-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_branch_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('curr', 'CURRENT_ACCOUNT'), ('savings', 'SAVINGS_ACCOUNT'), ('demat', 'DEMAT_ACCOUNT')], default='savings', max_length=50)),
            ],
        ),
    ]
