# Generated by Django 3.2.18 on 2023-02-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='color',
            new_name='account',
        ),
    ]
